### ISSUE TITLE
README is missing a step

### ISSUE THREAD

**Issue by rodrigob** [tensorflow/tfjs-converter#39]
Following the readme step by step, fails at step1.3 (Run the convert.py script) with

```
Traceback (most recent call last):
  File "scripts/convert.py", line 28, in <module>
    import write_weights as tfc
ImportError: No module named 'write_weights'
```

looking at the code, seems like some `../node_modules/deeplearn-src/scripts/` files should have been created through a missing step in the readme.

**Comment by pyu10055** [comment]
we have moved the conversion script to pip package, this issue is not longer valid.
