### ISSUE TITLE
Handling of Assert Ops ?

### ISSUE THREAD

**Issue by rodrigob** [tensorflow/tfjs-converter#42]
The SavedModel I am trying to convert generated, amongst others; the following message:

> Unsupported Ops in the model: Assert

I am wondering if tfjs-converted should not simply ignore Assert ops, and at best generate a warning rather than an error ? (I guess the same would go for Print ops)

**Comment by pyu10055** [comment]
We believe that the Assert op should not exist in the inference graph, we will remove the assert and other debug nodes from the graph during the conversion phase.

**Comment by dsmilkov** [comment]
This issue was moved to tensorflow/tfjs#55
