### ISSUE TITLE
Support for loading checkpoint files?

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs-converter#66]
Hello,

In deeplearn.js there was a `CheckpointLoader` that made it possible for you to recreate your model architecture at a low level in JS. What is the official tensorflowjs way to do this? As mentioned in your docs, sometimes it's not possible to load a SavedModel into JS because only certain ops are supported. 

Sorry if I missed a note in the docs somewhere for how to do this! Thanks for creating this amazing tool :)

**Comment by pyu10055** [comment]
If you want to load python trained model into tfjs, the official way is to save the python model in SavedModel format, and use the converter to generate the tfjs web format. 
The reason some of the python pretrained model won’t work in tfjs is tfjs has not implemented all TF ops, this will improve as tfjs improves. It is not caused by SavedModel format, the format itself is fully supported. I want to point out that checkpoint and meta files format has been deprecated. I will try to create a tutorial on how to convert existing python checkpoint files to SavedModel. 
Feel free to reopen if the above does not answer your questions.

**Comment by annxingyuan** [comment]
Hi Ping,

Thanks so much for your response. Are you saying it's no longer possible to manually recreate a model architecture in JS with pretrained weights? The use case I have in mind is to create a pedagogical tool that lets users explore what's going on in the different layers of a network. The way I was thinking about approaching this is to train a model in python, then recreate the architecture in JS, load in the pretrained weights, and make it possible to inspect the different layers in the browser.  From what I understand, the SavedModel format is somewhat sealed, which is why I wanted to use the checkpoint files approach that was available in deeplearn.js through its `CheckpointLoader`. 

Am I understanding things correctly? Is there any way to recreate a model in the browser in the way I'm describing with tensorflow js?

Thank you again!

**Comment by nsthorat** [comment]
Hi @annxingyuan, so it depends, do you actually need the weights themselves or are activations enough? 

Here are the three approaches:

1) Use the TensorFlow SavedModel converter. Using the `execute` method, you can specify an input and an output node name (the tensorflow node): https://github.com/tensorflow/tfjs-converter/blob/master/src/executor/frozen_model.ts#L116

Using this, you could execute and get an internal activation. The catch here is that you can't get *all* activations in a single pass, you'd have to execute multiple times if you want many internal activations. 

@pyu10055 - is there a simple way to get weights from a frozen model at the API surface?

2) Use the Keras model converter: https://js.tensorflow.org/tutorials/import-keras.html

With this, you can easily get activations by creating a new model that outputs an internal layer's activation, like we do here: https://github.com/tensorflow/tfjs-examples/blob/master/webcam-transfer-learning/index.js#L43-L46

@caisq who might be able to answer whether it's possible to get the weights themselves from a layer with the public API.

3) Use the deprecated checkpoint loader with the path I outline here: https://github.com/tensorflow/tfjs/issues/37

Hope this helps.

**Comment by pyu10055** [comment]
As @nikhil mentioned you can get activations with the execute method, and actually it allow you to provide a list of nodes, which means you can get any number of activations in one call. 

Currently the weights are not exposed directly in the FrozenModel class, but can be added easily.

Let me know what is your use case. Thanks.

**Comment by dsmilkov** [comment]
Hi @annxingyuan,

There is a method you can use which behaves like the legacy `CheckpointLoader`, that we don't expose in our API docs: [tf.loadWeights](https://github.com/tensorflow/tfjs-core/blob/master/src/weights_loader.ts#L47). You still have to use the converter to produce the weight files and the weights manifest which is needed by `tf.loadWeights` method.

**Comment by annxingyuan** [comment]
@dsmilkov @nsthorat @pyu10055 

Thanks everyone for providing all these solutions! I will try them out :)
