### ISSUE TITLE
Add tf.layers.conv2d_transpose support in SavedModel converter

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tfjs-converter#68]
I'm working on a CycleGAN project which relies on strided convolutions (as do most GANs, and many other models). It's written in TensorFlow's Python API with `tf.layers.conv2d_transpose`.

I saw that TensorFlow.js has [transposed strided convolutions](https://js.tensorflow.org/api/latest/#conv2dTranspose) but when converting the SavedModel with tensorflowjs_converter I get stuck with
```
Unsupported Ops in the model
StridedSlice
```
I guess I could rewrite the forward pass directly in TensorFlow.js but I'm curious why the converter didn't work? I guess it's because `conv2dTranspose` is fused while `tf.layers.conv2d_transpose` relies on a separate StridedSlice op.

**Comment by nsthorat** [comment]
Ping, can you take a look?

**Comment by dsmilkov** [comment]
This issue was moved to tensorflow/tfjs#52
